version: '3.8'

services:

  postgres:
    container_name: postgres
    image: postgres:14.0-alpine

    restart: on-failure

    env_file:
      - .env

    ports:
      - "5433:5432"
    networks:
      - postgres

    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: m0ckkingj4yy@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  # backend:
  #   container_name: test-backend
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - postgres
  #   restart: unless-stopped
  #   volumes:
  #     - /backend/node_modules
  #     - ./backend:/backend
  #   ports:
  #     - "3001:3001"
  #   env_file:
  #     - .env


networks:
  postgres:
    driver: bridge

volumes:
    postgres-data:
    pgadmin: