version: '3.8'

services:

  postgres:

    image: postgres:14.0-alpine

    restart: on-failure

    env_file:
      - .env

    ports:
      - "5433:5432"
    networks:
      - postgres

    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: m0ckkingj4yy@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres-data:
    pgadmin: